server.port=8080

# TODO  choose : [kafka]/[eventBus]/[rocketMq]/[rabbitMq],recommend  [eventBus] or  [kafka]
austin.mq.pipeline=kafka

# todo [xxl-job] switch
austin.xxl.job.enabled=true

# todo choose: [apollo]/[nacos] switch  ,if [apollo] and [nacos] both false, use local.properties
austin.apollo.enabled=false
austin.nacos.enabled=false

# TODO [hades] switch
austin.rule.engine.enabled=false

# TODO if windows os and need upload file to send message  ,replace path !
austin.business.upload.crowd.path=/home/mrawa/code/austin/data/upload/crowd/

# TODO Whether to enable [sensitive word filter] and set the [path] of sensitive words dictionary
austin.senswords.filter.enabled=true
austin.senswords.dict.path=classpath:sensitive-words.txt

austin.database.ip = localhost
austin.database.port = 2026
austin.database.username = mrawa
austin.database.password = password


austin.redis.ip = localhost
austin.redis.port = 6379


austin.kafka.ip = localhost
austin.kafka.port = 9092


austin.xxl.job.ip = localhost
austin.xxl.job.port = 9090